# Generated by Django 4.0.2 on 2022-02-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ('-date',)},
        ),
    ]
